### ISSUE TITLE
Not Working w/ HDT v0.13.14

### ISSUE THREAD

**Issue by smashedr** [ericBG/AnyfinCalculator#2]
This plugin does not seem to work with the current version of HDT v0.13.14

Clicking the Options button does nothing, and the damage calculator never shows up.

Windows 10 Pro x64.

**Comment by ericBG** [comment]
Just loaded up on my HDT 0.13.14, it seems to work. The Options button is not meant to do anything (I should probably make it pop up a messagebox to say something to that effect actually). Two things - are you sure the plugin itself is enabled? The damage range should be shown when you hover over "Anyfin can Happen" in your hand.
