### ISSUE TITLE
Second anyfin doesn't work

### ISSUE THREAD

**Issue by wisethug** [ericBG/AnyfinCalculator#3]
Hello ericBG ! 

The plugin is very good. However the second anyfin doesn't work when it comes down to telling how much dmg I have !

Any way to fix this ? 

Thanks

**Comment by ericBG** [comment]
As far as I know I fixed this issue in version 1.0.1, could you just please check whether you are using that version?

Thank you!

**Comment by wisethug** [comment]
The last one on the releases page. :(

**Comment by ericBG** [comment]
That's 1.0.0, try [v1.0.1](https://github.com/ericBG/AnyfinCalculator/releases/tag/v1.0.1).

**Comment by wisethug** [comment]
Hm, downloaded it, and in HS deck tracker the version displayerd is "1.0.0". Same bug happens :/

**Comment by ericBG** [comment]
Turns out that's just me being lazy, and not editing the version string (sorry). Would you be able to post what's on the HDT log? I can't reproduce this...

**Comment by ericBG** [comment]
Should be fixed with the new version.
