### ISSUE TITLE
Worked, then didnt.

### ISSUE THREAD

**Issue by Arro** [ericBG/AnyfinCalculator#4]
Hello,

I used this plugin today.  Early in a game, when I hovered over the Anyfin card, it showed in the top left corner.  (I think it said 4 damage.)  Later in the game, when I hovered over it, it showed nothing.  It was my turn.  Then, about 4 seconds later, when I hovered **off** of it, it showed up.  Finally, late game, when I believe it should have showed 14+ damage on my turn, it wouldn't show up at all.  

Any ideas why this would be?  I'm using 1.01.  Are there any logs I can look at?

**Comment by ericBG** [comment]
Hey,

I seem to be getting this issue from a few people recently. 1.0.1 works for me and I'm on the latest stable HDT, so I'm not quite sure why this is. But yes, the logs would be really helpful! They're in "%appdata%\HearthstoneDeckTracker\Logs". I'd appreciate it if you could give me one :) Thanks!

**Comment by ericBG** [comment]
Should be fixed with the new version.
