### ISSUE TITLE
This plugin doesn't work for me with HDT v.0.14.0

### ISSUE THREAD

**Issue by Binori** [ericBG/AnyfinCalculator#5]
![screen](http://i.imgur.com/g1PmL0B.jpg)

**Comment by ericBG** [comment]
Have you got version 1.0.2? I'll investigate just a second!

**Comment by Binori** [comment]
Yes, I found your plugin today (I use HDT quite long) so I downloaded newest version.
AFAIR in yesterday HDT update to newest v.0.14.0 the @Epix37 wrote something in Update Changelog that some plugins couldn't work because he changed something "bla bla bla" ;)) Maybe this is a track to follow.

**Comment by azeier** [comment]
`CardEntity` no longer exists, all the zone lists in `Player` are now `IEnumerable<Entity>`.

**Comment by ericBG** [comment]
That will do it, working on a quick fix. Thanks Epix!

**Comment by ericBG** [comment]
Here's the release: https://github.com/ericBG/AnyfinCalculator/releases/tag/v1.0.3

**Comment by Binori** [comment]
Thx! It works now but I have another bug. I will create the topic.
