### ISSUE TITLE
1.0.3 - Incorrect Anyfin damage calculation

### ISSUE THREAD

**Issue by Binori** [ericBG/AnyfinCalculator#6]
Hi,

Looks like plugin doesn't count Anyfin damage correctly.

See screen below. 
Graveyard: 1 Bluegill Warrior, 1 Murloc Warleader
Board: Old Murk-Eye

Plugins shows 8 damage but correct value is 10.

![screen](http://i.imgur.com/bqeD1M3.jpg)

**Comment by ericBG** [comment]
[This](https://github.com/ericBG/AnyfinCalculator/releases/tag/v1.0.4) release should've fixed your issue.
